[preface]
== Forord


[quote,Kristen Nygaard]
____
Å programmere er å forstå.
____


Hensikten med denne boka er å prøve å forklare hvordan man kan lage et 
dataprogram. Det å lage et dataprogram kan kanskje sammenlignes med det å 
skrive en roman eller konstruere en større eventyrfortelling. Alle skjønner at 
det ikke går ann å lage en komplett fasit til hvordan man skal gjøre dette. 
Men, det finnes likevel en del rettningslinjer og kjøreregler. Det finnes i alle 
fall en del generelle råd og vink. Slik er det også når man skal lage et 
dataprogram. 

Det som kanskje skiller rådene i denne boka litt fra det som 
allerede finnes, er at disse er skrevet på norsk, og på en 
muntlig form, og primært rettet mot skoleelever. Jeg tenker at en ungdom som 
går på ungdomsskolen og som skjønner hvordan en enkel matematisk funksjon 
fungere, kan lære litt om programmering ut fra det som står her.

Altså; skjønner du dette, er det bare å kjøre på:

----
En funksjonen er definert ved uttrykket f(x) = x + 1  
Gitt at x = 2

Får vi at

f(x) = x + 1
f(2) = 2 + 1 
f(2) = 3
----

Dataprogrammet er *x+1*. Input til dataprogrammet er *2*. Og svaret fra 
dataprogrammet er *3*.

Dette er programmering. Værre er det i bunn og grunn ikke. 

Alt en datamaskin gjør er å automatisere denne prosessen, slik at den kan 
gjentas et ufattelig antall ganger med forskjellig input. Det å programmere 
handler om å handtere kompleksitet. Og for å handtere kompleksitet må vi 
forenkle og abstrahere, og for å kunne forenkle og abstrahere må vi kunne 
modellere og analysere. 

Denne boka prøver å gi en introduksjon til disse ulike
begrepene. Dette skal vi få til ved å relatere disse abstrakte utrykkene 
til konkrete problemer som vi støter på i forbindelse med at vi utvikler to 
dataprogram. Det første dataprogrammet som vi skal lage, er et program som 
hjelper oss å avvikle et skirenn. Det andre programmet vi skal lage er  
et _SpaceInvader_ -lignende spill. 

Du må ikke lure deg selv til å tro at du 
kan lære deg å programmere, uten at du jobber deg gjennom alle eksemplene som 
vi skal se på. Programmering er på sett og vis også et handtverk, og et 
handtverk må øves inn for å kunne mestre det. Og for de fleste 
av oss finnes det ingen snarveier i så måte. 


[quote,En hver voksen person]
____
Suksess skyldes 
ikke talent, men 
hardt arbeid og litt flaks.
____



Årsaken til at du bør sette deg litt inn i hvordan man lager et dataprogram, 
er fordi datamaskiner blir en stadig viktigere del av tilværelsen. Vi omgir oss 
med de nærmest hele tiden, og de utfører oppgaver 
på vegne av oss stadig vekk. Ringer du med en mobiltelefon bruker du egentlig en 
datamaskin. Kjører du en tur med en ny bil, bruker du flere hundre 
datamaskiner. Ser du på TV eller bruker Internet, er flere tusen i sving for å 
utføre oppgaver på vegne av deg. Derfor er det viktig at flest mulig har en 
forståelse av hva en datamaskin er, og hvordan denne kan programmeres.

Denne boka prøve å gi deg grunnleggende innsikt i hvordan du kan 
programere i et programmeringsspråket som heter _C_. Du trenger egentlig ingen annen bakgrunn 
enn litt nysgjerrighet. Når du har jobbet deg gjennom boka, vil du sitte igjen 
med en god forståelse av hva det innebærer å lage programvare. De verktøyene og 
metodene som omtales, er for det meste grunnleggende teknologi som har vært med 
oss i mange ti-år, men som fortsatt er _state-of-the-art_.  



