== Innputt og utputt

Som nevnt i starten; all databehandling dreier seg rundt det faktum at du sender 
noe data inn i en prossess. Denne prosessen utfører deretter en eller flere beregninger, for 
til slutt å returnerer et svar tilbake. 

Derfor kan det være lurt å forstå hvordan man, så enkelt som mulig, kan gjøre dette ved hjelp 
av _C_-kode. Det er læringsmålet med dette kapitlet.


.Læringsmål
----
 - innputt 
 - beregning
 - utputt 
----


Innputt og utputt er i forhold til operativsystemet footnote:[Windows og Linux 
er eksempler på operativsystem, det vil si det systemet som sørger for at 
datamaskinen vår fungerer; skjerm, mus, tastatur etc. Det er operativsystemet 
som starter de ulike programmene som kjører på datamaskinen.]. Det vil si at det 
er operativsystemet, som når det starter programmet vårt, gir oss innputten. Det er det 
samme operativsystemet som mottar utputten når programet avsluttes. 
 
Dette er innputt og utputt i sin enkleste form. Utover dette kan vi også si at vi har innputt 
i form av data fra mus og tastatur, og utputt i form av informasjon på skjerm og høytalere etc. Dette 
kommer vi tilbake til. Aller først skal vi se på den aller enkleste formen for 
innputt og utputt.
  
[source,c]  
.test.c (eksempel 2)
---- 

int main () { #<1>
        
    return 0; #<2>
    
}
----
<1> Programmet starter her, og mottar innputt.
<2> Programmet avslutter her, og sender tilbake noe utputt.


Lagre denne koden i ei fil kalt; _test.c_ og skriv:

 gcc test.c

Kjør deretter programmet som ble produsert. Nå skal du ikke se noe på skjermen. 
Men, det betyr ikke at programmet ikke returnerer noe tilbake til det 
programmet som startet det.

Ok, så hva skjer egentlig her? Jo, dette er det enkleste C -programmet som er 
mulig å skrive, og alt programmet gjør er å returnere tallet null tilbake til den 
prosessen som startet programmet. Likevel er det mye å lære;
først merker vi oss at det er en eller annen prosess som starter det programmet vi lager. 
Denne prosessen kjører gjerne i et eller annet operativsystem. Det er det samme 
om vi snakker om Linux, Mac eller Windows; et annet program starter vårt program. 

Tenk tilbake på dette:

 innputt → beregninger → utputt

Det betyr at når du starter progammet, skal du kunne gi noe _“innputt”_ til 
programmet, som deretter skal _“gjøre et eller annet”_ for til slutt å gi 
tilbake noe _“utputt”_.

Vi venter litt med _“innput”_ -delen og ser nærmere på _“gjøre et eller annet”_ -delen 
og _“utputt”_ -delen.

I vårt tilfelle ovenfor, er _“gjøre et eller annet”_ -delen å returnere tallet 
null. Men, hvordan får vi tak i resultat? 

Da må vi gå til det programmet som starter programet vårt. Og det programmet er 
Cygwin terminal-programmet. Det er jo i dette programmet vi skriver:

 ./a.out
 
for å kjøre _C_-programmet vårt.

Det vil varierer litt hvordan man får tak i retur -verdien fra et program. I vårt 
tilfelle hvor vi bruker Cygwin, kan du få tak i returverdien ved å skrive:

 echo $? 

For å oppsummere: 
 
 gcc test.c
 ./a.out
 echo $? 
 0
 
Det vi har gjennomført ovenfor, er å kode, kompilere, kjøre samt sjekke 
resultatet fra det enkleste _C_-programmet som er mulig å lage. Alt programmet 
gjør er å returnere tallet null. Vi bruker 
kommandoen _echo $?_ for å vise det tallet som ble returnert til 
skallet footnote:[Et terminalvindu kan også omtales som et skall, siden det 
engelse ordet _shell_ er mest vanlig å bruke på slike typer dataprogram. 
linuxcommand.org : What is "the shell"? _Simply put, the shell is a program that 
takes your commands from the keyboard and gives them to the operating system to 
perform. In the old days, it was the only user interface available on a Unix 
computer. Nowadays, we have graphical user interfaces (GUIs) in addition to 
command line interfaces (CLIs) such as the shell._]. 
 
Prøv nå å endre test-programmet til å returnere tallet 5

[source,c]  
.test.c (eksempel 3)
---- 

int main() {

	return 5;
    
}

---- 


Lagre koden og skriv

 gcc test.c

for deretter å kjøre programmet.

 ./a.out

Skriv kommandoen:

 echo $? 


for å se returverdien fra programmet.

Som nevnt, alle _C_ -program starter ved at en annet program  
kaller opp funksjonen _"main"_.  Denne funksjonen returnerer et heltall. 
Dette er definert ved at det står _"int"_ foran  _"main"_. Det er også mulig å sende 
informasjon inn til _"main"_. Det skal vi se på etter hvert. Men, først skal vi 
dvele litt med med begrepet _"funksjon"_.

Vi kjenner til begrepet funksjon fra matematikken. Der ser gjerne en funksjon slik ut:

....

 f(x) = x + 1

 Sett inn x = 2

 f(2) = 2 + 1
 f(2) = 3

 input → beregninger → output
 2 → 2 + 1 → 3

....

=== Variabler

Tidligere pratet jeg i bokser og variabler. Jeg sa at et dataprogram kan sees på 
som instruksjoner som endrer på innholdet i ulike bokser med data. _"int"_ er en slik 
boks med data som kan inneholde et heltall.  En måte å se 
på dette, kan være som følger: terminalprogrammet har en boks hvor returverdien 
kan lagres. Når terminalprogrammet kjører programet vårt, blir returverdien 
lagt i denne boksen. Dermed kan terminalprogrammet etterpå vise verdien på skjermen. Programmet 
vårt kan sees på som en funksjon som hele tiden returnerer tallet 5, helt uavhengig av hva som sendes inn som intput.


....

 f(x) = 5

 f(1) = 5
 f(2) = 5
 f(3) = 5

....

La oss modifisere programmet slik at det legger sammen to tall. 

[source,c]  
.test.c (eksempel 4)
---- 

int main() {

	int a = 2;
	int b = 3;
	int c = a + b;
    
	return c;
    
}

----

Jeg oppretter tre bokser av typen _int_. (int -> integer = heltall). 
Legger tallet 3 i den første, tallet 4 i den andre og summen i 
den tredje. Til slutt returnerer jeg med det tallet som måtte ligge i den 
tredje boksen.

Legg merke til at vi kan kalle databoksene for hva vi vil. Jeg har valgt å kalle dem _a_, _b_ og _c_. 

Skriv inn koden, og test ut. 

Neste steg for oss blir å modifisere programmet slik at det kan ta i mot 
input fra skallet. Eller input fra terminal-programmet om du vil. 

Legg merke til at når du skal kompilere _C_-koden som ligger i fila _test.c_, så 
oppgir du dette som input til programmet _gcc_, på denne måten:

 gcc test.c

Dette viser inputt skriver du i tur og orden etter navnet på selve programmet. I vårt tilfelle skriver vi noe slikt som dette:

 a.exe 2

Da vil vi starte programmet med tallet 2 som input. Men, hvordan får vi tak 
i dette tallet inne i programmet? 

Modifiser _test.c_ til å se slik ut:

[source,c]  
.test.c (eksempel 5)
---- 

int main ( int argument_antall, char *argument_vektor[] ) {

	int x = atoi(argument_vektor[1]);
    
	return x + 1;
    
}

----

Kompiler og test ved å utføre disse kommandoene:

....

 >gcc test.c
 >a.exe 1 
 >echo $?
 >2

 >a.exe 2
 >echo $?
 >3

 >a.exe 3 
 >echo $?
 >4

....
 
Jepp, her skjer det ting. Nå klarer vi å gi input til programmet vårt, vi utfører 
ei enkel beregning ved å addere tallet 1 til det tallet som kommer inn, og vi 
returnerer med svaret. Men, det som en gang var verdens minste C -program, har nå 
blitt litt mer komplisert. Vi starter med: 

 int argument_antall 
 char * argument_vektor[]  

Dette er to bokser eller to variabler. Den første er av typen _int_.
Det betyr at i variabelen som heter _argument_antall_, ligger det 
et heltall. Dette heltallet angir antall argumenter inn til programmet. Egentlig 
angir dette tallet antall argumenter, pluss 1, siden navnet til programmet også 
regnes med når antallet input-argumenter telles opp. Det betyr i praksis at når 
du skriver:

 a.exe 3

så vil innholdet i _antall_argument_ være lik 2, siden det første argumentet 
er _'a.exe'_ og det andre er _3_.

Ved hjelp av variabelen _argument_antall_ vet vi hvor mange argumenter som 
kommer inn til programmet. For å få tak i selve argumentene må vi se nærmere 
på variabelen som heter _argument_vektor_. Denne inneholder en 
tabell med pekere av typen _char_, som peker mot en tekst-representasjon av de 
ulike argumentene.



_... For å gå tak i selve argumentene må vi se nærmere på variabelen som heter 
argument_vektor. Denne inneholder en tabell med pekere av typen ‘char’, som peker mot en tekst-representasjon av de ulike argumentene. ..._


I den siste setningen dukket det opp en rekke nye begreper som vi skal bruke 
resten av kapittelet til å lære oss. Mye av dette vil fortone seg komplisert, men ei fattig trøst er
at når du får en forståelse dette, så har du fått en grunnleggende forståelse for hvordan et hvert dataprogramm egentlig fungerer.
Som tidligere nevnt, dette er kanskje en av de store fordelene ved å lære seg _C_ -programmering.

Vi nå ta for oss datatyper, tabeller og pekere.

=== Datatyper 


Vi starter med typen _char_. Vi vet fra før av at vi kan ha en variabel av typen _int_. 
Det betyr at innholdet i variabelen kan være et heltall. Variabler av typen _char_ er forsåvidt også heltall, men historisk 
sett var disse heltallene tenkt å representere bokstaver eller tegn.

Det betyr at, ønsker du deg en variabel som skal kunne lagre en bokstav, for 
eksempel en _a_, så skriver du det slik:

[source,c]  
---- 
char min_boks = ‘a’
----

Her blir det opprette en variabel som heter _min_boks_. Denne variabelen er av 
typen _char_ og den tilordnes verdien _a_. 

Om verdien er et tegn, må dette stå med apostrof.

Det som er viktig å få med seg her, er at vi har to ulike datatyper; en som 
heter _int_ og som kan inneholde heltall, typisk i settet [1 .. 32767] og en som 
heter _char_ og som kan inneholde heltall, typisk i settet [1 .. 255]. At 
tegnet '_a_' egentlig somregel er det samme som tallet 97, er noe hokus-pokus vi skal komme tilbake til senere.

=== Tabeller

Det er mulig å sette samme flere variabler, slik at de danner en tabell. Vi kan 
ha en tabell av _int_ og en tabell av _char_.

Når vi skal lagre et ord i en variabel, må vi først lage en tabell av _char_, siden 
et ord består av flere tegn. En slik sammenstilling av tegn kaller vi for _en streng_. For å 
angi at vi ønsker en tabell av _char’s_ skriver vi 
tegnene [] bak variabelnavnet, slik:

[source,c]  
---- 
char min_streng[] = “Hei”;
----

Sleve strengen angis med anførselstegn.

Hvert enkelt tegn i strengen har sin egen plass i tabellen.

                       0   1   2   
                     +---+---+---+
 char min_streng[] = | H | e | i |
                     +---+---+---+


Vi kan hente ut hvert enkelt tegn fra tabellen, og plassere de i sine egne variabler, om vi skulle ønske.

[source,c]  
---- 
char min_bokstav_h = min_streng[0]
char min_bokstav_e = min_streng[1]
char min_bokstav_i = min_streng[2]
----

Vi ser at det er mulig å hente ut hvert enkelt tegn, ved å angi 
indeksen (eller plasseringa) til den aktuelle bokstaven i tabellen.

.En streng er en tabell av tegn.
NOTE: For å lagre en tekststreng; ord eller setninger i _C_, 
      bruker vi en databoks som består av ei samling av databoksen _char_. Ei slik 
      samling av tegn kaller vi for en tabell. Vi bruker tegnene ‘[‘ og  ‘]’ bak 
      variabelnavnet, for å angi at dette er en tabell av variabler.



      
Tre variabler som hver representerer ett tegn (char):

[source,c]  
---- 
char a = ‘h’
char b = ‘e’
char c = ‘i’
----

Tre variabler, som hver representerer ei samling tegn, altså en array av tegn (char’s):

[source,c]  
---- 
char a[] = “Hei verden”
char b[] = “Hello world”
char c[] = “Bonjour monde”
----

Ok, nå er vi kommet et stykke på vei til å forstå setningen: 

_... For å gå tak i selve argumentene må vi se nærmere på variabelen som heter 
argument_vektor. Denne inneholder en tabell med pekere av typen ‘char’, som peker mot en tekst-representasjon av de ulike argumentene. ..._

Vi skjønner det med _tekst-representasjon_. Det vil si at vi klarer å lage en variabel 
som inneholder en tekst. Det gjør vi ved å lage en tabell av _char_ -variabler, slik:

              0   1   2   3   4   5   6   7   8   9   
            +---+---+---+---+---+---+---+---+---+---+
 char a[] = | H | e | i |   | v | e | r | d | e | n |
            +---+---+---+---+---+---+---+---+---+---+

              0   1   2   3   4   5   6   7   8   9   10  
            +---+---+---+---+---+---+---+---+---+---+---+
 char b[] = | H | e | l | l | o |   | w | o | r | l | d |
            +---+---+---+---+---+---+---+---+---+---+---+

              0   1   2   3   4   5   6   7   8   9   10  11  12  
            +---+---+---+---+---+---+---+---+---+---+---+---+---+
 char c[] = | B | o | n | j | o | u | r |   | m | o | n | d | e |
            +---+---+---+---+---+---+---+---+---+---+---+---+---+

Men, vi skal ha en tabell av pekere, som peker mot data av typen char.

Nå drar det seg litt til her. 

=== Pekere 

For å forstå hva en peker er, må vi gå litt nærmere inn på hvordan en datamaskin 
egentlig fungerer. Du har sikkert hørt om RAM (random access memory), eller bare kort og godt; _minne_. 
En datamaskin har en viss mengde fysisk RAM, og mange tenker kun på minne når de 
skal angi hvor stor en datamaskin er. De variablene vi har pratet om ovenfor, 
ligger i minnet til datamaskinen. Dette minnet kan vi se på som en tabell av 
databokser, hvor hver slik boks har sin egen adresse, på samme måte som hver 
bokstav i en streng har sin egen index.

 +-----+-----+
 | 001 |  H  |
 +-----+-----+
 | 002 |  e  |
 +-----+-----+
 | 003 |  i  |
 +-----+-----+
 

Dermed kan vi se på strengen vår på to måter. Både hvordan den er lagret i variabelen  
i programmet vårt, og hvordan den egentlig er lagret i minnet.

[source,c]  
---- 
char a[] = “Hei”
----

              0   1   2  
            +---+---+---+
 char a[] = | H | e | i |
            +---+---+---+

 +---------------------+-----+
 | 9223372036854775800 |  H  |
 +---------------------+-----+
 | 9223372036854775808 |  e  |
 +---------------------+-----+
 | 9223372036854775816 |  i  |
 +---------------------+-----+


Ovenfor har jeg brukt noen store tall for å vise de ulike minne -addressene. Om du har 
en 64 bits datamaskin, som for tiden er det normale, kan datamaskinen din nå 2^64 slike 
minne -adresser. Dette er et stort tall, og viser litt hvor kraftig en datamaskin 
egentlig er.  
 
 Antall mennesker på jorden         7 000 000 000 
 Antall menneskehårstrå       700 000 000 000 000 
 2^64 er lik           18 446 744 073 709 551 615 
                  

Når man programmerer i _C_, kan man nå innholdet til de ulike adressene ved å bruke en 
konstruksjon som heter _peker_. 

Om jeg ønsker meg en slik peker, som peker på strengen “Hei” ovenfor, kan jeg skrive

[source,c]  
---- 
 char *min_peker = &a
---- 

Verdien som nå ligger i _min_peker_ vil være 9223372036854775800, altså minneadressen  
til den første bokstaven i strengen “Hei”.

Strengen “Hei” starter med adressen til den første bokstaven, og 
varer helt til det dukker opp et null-tall. 

Ampersand forann en variabel, betyr med andre ord; gi meg minneadressen til denne variabelen.


.Databokser av ulik type
NOTE: Når vi programmerer kan vi se på variablene som bokser, som kan inneholde 
      ulike typer data. Hver type boks kan lagre sin type data. Og hver slik 
      boks har sin unike adresse. Denne adressen kan man hente ut ved å sette en 
      ampersand forann navnet til boksen.      
 


[source,c]  
---- 
 char a = ‘h’
----  

Disse boksene ligger i minnet til datamaskinen. Enhver minneplassering har sin adresse. 

 +---------------------+-----+
 | …                   |     |
 +---------------------+-----+
 | 9223372036854775800 |     |
 +---------------------+-----+
 | 9223372036854775808 |  h  |
 +---------------------+-----+
 | 9223372036854775816 |     |
 +---------------------+-----+
 | …                   |     |
 +---------------------+-----+

Om vi ønsker å få tak i denne adressen, skriver vi en ampersand ‘&’ forann variabelnavnet. 
Adressen kan deretter lagres i en egen databoks som vi kaller for en peker. En peker har en type, for å vise hvilken type databoks som gjemmer seg bak adressen.

At databoksen inneholder en peker, angir vi ved å skrive ei stjerne foran variabelen når vi deklarerer den. 

[source,c]  
---- 
 char *min_peker_til_a = &a
---- 

                         +---------------------+
 char *min_peker_til_a = | 9223372036854775808 |
                         +---------------------+

[source,c]  
----  
 char b = *min_peker_til_a;
----  

 char a og char b inneholder nå begge verdien “h”.  

Legg merke til dette:

 9223372036854775808 = min_peker_til_a;
 ‘h’ = *min_peker_til_a;

Altså, om vi skal hente verdien i den databoksen som gjemmer seg bak adressen, 
må vi oppgi ei stjerne forann variabelnavnet. Om vi ikke gjør det, henter vi ut selve adressen.

På samme måte som vi kan ha en tabell av databokser av typen char, kan vi ha en 
tabell av databokser av typen _peker til char_.

a er en databoks av typen char, som inneholder tegnet ‘h’

[source,c]  
---- 
 char a = ‘h’;
---- 
 
b er en databoks av typen _tabell av char_, som inneholder strengen; “hei”

[source,c]  
---- 
 char b[] = “hei”;
---- 

Ut fra denne tabellen kan vi hent hver enkel databoks av typen char, slik:

[source,c]  
---- 
 char boks_for_h = b[0];
 char boks_for_e = b[1];
 char boks_for_i = b[2];
---- 
 
Det samme kan vi gjøre med datatypen _peker til char_, slik:

[source,c]  
---- 
 char a = ‘a’
 char b = ‘b’
 char c = ‘c’

 char *pa = &a;
 char *pb = &b;
 char *pc = &c;
---- 

Disse kan vi legge i en tabell, slik:

[source,c]  
---- 
 char *tabell_av_pekere[] = {pa,pb,pc};
---- 
 
på samme måte som da vi opprettet en streng av flere tegn.

Vi henter ut verdien til det pekeren peker på, ved å sette ei stjerne foran variabelnavnet.

[source,c]  
---- 
 char a2 = *pa
---- 
 
eller som i bildet ovenfor, hvor den samme pekeren ligger som første element i en tabell-variabel

[source,c]  
---- 
 char a2 = *tabell_av_peker[0]
----  


.Databokser av ulik type
NOTE: Ok, kjapp oppsummering igjen. En databoks har et navn og en type. Navnet bestemmer 
      vi som lager dataprogrammet. Typen er noe som er definert i programmeringsspråket. Vi 
      som programmerere velger hvilken type vi ønsker å bruke. En databoks ligger egentlig 
      lagret en plass i minnet. Vi har to måter å nå en databoks på. Enten ved å henvise til 
      navnet på databoksen, eller ved å bruke en peker som peker mot den adressen hvor databoksen ligger i minnet. 

Dette er på mange måter kjernen i C-programmering. Det at vi kan programmere med pekere, 
som kan peke _hvor som helst_, gir oss mange muligheter. På godt og ondt.

Tilbake til main -funksjonen vår. Der har vi at det første argumentet (_int argument_antall_) 
angir antallet input -argumenter, og det andre argumentet (_char *argument_vektor[]_)  
er en tabell av pekere til tekst -strenger. Husk at en tekst -streng er en tabell av databokser av typen char.

Det betyr at om vi lager oss et program som heter _a.exe_, som tar inn to tall som parametre, som vist her:

 a.exe 2 3

vil _argument_antall_ og _argument_vektor_, se slik ut:

                       +---+
 int argument_antall = | 3 |
                       +---+

                           +-----+-----+-----+
 char *argument_vektor[] = | 032 | 040 | 048 |
                           +-----+-----+-----+

Hvor det tenkte, litt forenkla, dataminnet ser slik ut: 

 +-----+---------+
 | …   |         |
 +-----+---------+
 | 032 | ‘a.exe’ |
 +-----+---------+
 | 040 |  ‘2’    |
 +-----+---------+
 | 048 |  ‘3’    |
 +-----+---------+
 | …   |         |
 +-----+---------+
 
Dette betyr at inne i main -funksjonen vet vi hvor mange argumenter som kommer inn, 
og vi vet hvordan vi kan plukke dem ut fra argument_vektor -variabelen.

Om jeg ønsker å vite hva programmet heter, kan jeg hente det ut slik;

[source,c]  
---- 
 char *a = argv[0]
----  

Variablen _a_ vil nå peke mot strengen "a.exe". Det første tallet kan jeg hente ut slik:

[source,c]  
---- 
 char *b = argv[1];
 int t1 = atoi(b);
---- 
 
og det andre slik

[source,c]  
---- 
 char *c = *argv[2];
 int t2 = atoi(c);
----  

Husk på at det er tekst -strenger vi henter ut fra _argument_vektor_ -tabellen. 
Når det gjelder navnet til programmet, altså det første argumentet, så er det 
en tekststreng. Denne variabelen er grei. Men, når det gjelder de to tallene må 
vi gjøre om datatypen fra char til int. De databoksene vi får ut fra _argument_vektor_
 er databokser som inneholder en tekst -streng av tallene. 
Her kommer funksjonen ‘atoi()’ inn i bildet. Denne funksjonen omgjør en databoks som 
innholder en tekstrepresentasjon av et tall, om til en databoks som inneholder en 
heltallsrepresentasjon. atoi er et akronym for ascii-to-integer. Om den 
tekststrengen som sendes inn til atoi skulle vise seg å ikke innholde et tall, vil 
funksjonen retunere verdien null.

Jeg skal kjapt prøve å forklare litt hva ascii er:

_American Standard Code for Information Interchange er en måte å kode bokstaver på. 
Husk på at en datamaskin egentlig bare kan forstå tall som er kodet i det binære tallsystemet, 
altså kun tallene; null og ett. Ved hjelp av tallene null og ett kan vi kontruere alle heltall, 
og vi kan lage systemer for å konstruere desimaltall. På samme måte må vi lage systemer for å 
representere tekst. Vi kan for eksempel si at desimal -tallet 65 skal bety bokstaven ‘A’. 
Det er nettopp det ascii definerer for oss, samt en rekke andre tegn og bokstaver._

Når du skriver

 char min_boks = ‘A’

legger du _egentlig_ tallet 65 inn i denne boksen.

65 er ascii-verdien for stor ‘a’. Tilsvarende har vi at ascii -verdien for tegnet ‘2’ 
er desimaltallet 50. Om vi ønsker å omgjøre teksten ‘2’ om til  tallet to, må vi 
bruke konverterings -funksjonen _atoi_. 

Bottom line her er at du må gjøre om tekst-representasjonen av tallet til 
heltalls -representasjonen av tallet, og dette utføres ved hjelp av funksjonen _atoi_. 

Nå skal vi ha et fiks ferdig _C_-program som skal kunne legge samme to tall:

[source,c]  
.test.c (eksempel 6)
---- 
 int main(int argument_antall, char *argument_vektor[]) { 
 
	 if (argument_antall != 3){ 
        return 0;
     }
     
	char *a = argument_vektor[0];
	char *b = argument_vektor[1];
	char *c = argument_vektor[2];
	
	int t1 = atoi(b);
	int t2 = atoi(c);
    
	return t1 + t2;
    
 }
----


Legg merke til at jeg sjekker innholdet i databoksen _argument_antall_. Om innholdet 
ikke er tallet 3, returnerer jeg tallet 0 for å indikere at brukeren har tastet 
inn feil antall argumenter. 

Om innholdet er 3, henter jeg ut de tre argumentene og gjør om de to siste til heltall. 
Til slutt adderes disse, og summen blir returnert tilbake til terminalprogrammet.

Dette er faktisk et ganske fiks ferdig program, takket være den enkle sjekken helt i 
starten, hvor vi sjekker at antallet argumenter er 3 før vi går videre. 

Prøv å ta bort denne sjekken, og kjør programmet ut noen inputparametre. Hva skjer? 

(Det som skjer er at vi henter noen databokser; b og c, ut fra minne som _ikke eksiterer_, 
eller ikke tilhører vårt program. Da vil programmet ganske sikkert feile.)

En lite problem med dette programmet, er at vi antageligvis bare kan 
returnere tall opp til 256, eller èn byte. Det vil si at om du legger sammen to tall 
hvor summer blir større en 256, vil det tallet som fremkommer på skjermen ikke være rett, 
siden du bare vil se den første byten av tallet. Dette har med å gjøre hvordan c-programmet 
vårt sender svaret tilbake til terminalprogrammet, og som nevnt så gjør vi det på en veldig minimalistisk måte nå.

Derfor skal vi innføre en kjekk liten funksjon som heter _printf_. Denne lar oss selv 
skrive ut tallet på skjermen.  _printf_ er så grunnleggende for en rekke programmeringsspråk, 
at den har fått sin egen wiki-side på Internett. Dette kommer av at mange programmeringspråk 
har behov for å kunne skrive ut en tekststreng på skjermen. I tillegg til selve teksten, 
ønsker man som oftes å putte på andre datatyper, typisk tall, i samme slengen. Man formaterer 
teksten litt, før den skrives ut. Derav navnet _printf_, som er en forkortelse for; “_print formatert_”. 

For å kunne bruke denne funksjonen må du skrive denne linja øverst i kodefila di:

[source,c]  
---- 
#include <stdio.h>
---- 

På den måten forteller du til kompilatoren at du ønsker å bruke en funksjon som 
allerede eksisterer, og at definisjonen på denne ligger i ei fil som heter _stdio.h_

Om du ønsker å skrive ut en enkel tekst ved help av _printf_, kan du skrive

[source,c]  
---- 
printf (“Hello world”);
---- 

Om du ønsker å skrive ut en formatert tekst, må du inn med noen koder. 
Med _formatert tekst_ menes at man kan putte inn verdier som ligger i ulike databokser, 
inn i tekststrengen, før den skrives ut på skjermen. For eksempel, så har vi sett 
at det er mulig å lagre heltall i databokser av typen _int_. Om vi ønsker å formatere 
verdien til en slik databoks, inn i en tekststreng, før denne skrives ut på skjermen, 
kan vi gjøre dette slik:

[source,c]  
---- 

int min_boks = 123;

printf (“Verdien til databoksen min_boks er %d”, a);

----

Dette vil resultere i følgende setning på skjermen:

 Verdien til databoksen min_boks er 123

Legg merke til at på samme måte som main er en funksjon som tar inn to parametre, 
er også printf en funksjon som tar inn ulike parametre. I vårt tilfelle er disse parametrene en tekststreng og en databoks for heltall.

Funksjonen _printf_ er laget slik at den bytter ut ulike koder i tekststrengen, 
med verdien i de ulike variablene som kommer etter tekststrengen. For eksempel, 
om man setter inn denne koden; ‘%d’, så forventer _printf_ at det skal komme en 
variabel av typen _int_ like etter tekststrengen.

Det er mulig å definere flere variabler som skal formateres inn i tekststrengen. 
Det er bare å putte på, i rekker og rad:

[source,c]  
---- 

 int a = 123;
 int b = 456;
 printf (“Verdien til a er %d og verdien til b er %d”, a, b);

---- 
 
Dette vil resultere i følgende setning på skjermen:

 Verdien til a er 123 og verdien til b er 456

Man kan bruke andre typer databokser, som for eksempel en tabell av chars, som 
vi kjenner som en streng. Da må vi bruke koden ‘%s’ som vist her:

[source,c]  
.test.c (eksempel 7)
---- 

 char a[] = “hei”;
 
 int b = 2;
 int c = 3;
 int d = b + c;
 
 printf (“a = %s b = %d c = %d d = %d”, a, b, c, d);

---- 

=== Komplett program

Vi nærmer oss nå slutte på kapittelet “Innputt & utputt”, hvor vi hovedsakelig 
har tatt for oss egenskapene til funksjonen _main_; hvordan vi får data inn til programmet og hvordan programmet gir svar 
tilbake til den prosessen som startert det, typiskt et terminalprogram. 

_main_ er funksjonen hvor et _C_-program starter. Her kommer _kallet_ fra 
operativsystemet, og her kan det komme et sett med inputargumenter inn til 
programmet vårt. Vi har lært at i alle fall navnet til programmet kommer inn som 
argument. Det kan komme flere argumenter. Vi har også lært at _main_-funksjonen 
kan returnere verdien til et heltall, tilbake til operativsystemet. Somregel 
brukes denne verdien til å indikere tilbake “_hvordan det gikk_”; om programmet 
feilet, manglet noen inputargumenter etc.

Helt til slutt viser jeg et komplett eksempel som bruker alt dette. 

[source,c]  
.test.c (eksempel 8)
---- 

#include <stdio.h>

int main(int argc, char *argv[]) {    

    char *navn = argv[0];
    
    if (argc != 3) {
        printf("\nBruk: %s t1 t2 \n", navn);
        printf("\n      hvor t1 og t2 er to heltall ");
        printf("som er > 0\n\n");    
        printf("Programmet adderer to tall og ");
        printf("skriver summen ut paa skjermen.\n");
        return 1;
    }
    
    char *a = argv[1];
    char *b = argv[2];
    
    int t1 = atoi(a);
    
    if (t1 == 0) {
        printf("\nFeil: t1 maa vaere et heltall > 0\n");
        return 1;
    } 
    
    int t2 = atoi(b);
    
    if (t2 == 0) {
        printf("\nFeil: t2 maa vaere et heltall > 0\n");
        return 1;
    }
    
    int t3 = t1 + t2;
    printf ("Summen av %d og %d er %d\n", t1, t2, t3);
    
    return 0;
    
}

---- 

Utover det vi har lært tidligere, ser du at jeg har puttet inn en ny kode i 
“format-strengen” til _printf_. Den nye koden er “\n” som forteller at _printf_ skal skrive ut et linjeskift (new line).

I tillegg sjekker jeg returverdien til funksjonen _atoi_. Om denne er null, er det 
en viss sannsynlighet for at brukeren ikke har oppgitt et heltall. Han eller hun har i 
alle fall ikke oppgitt et heltall som er større enn null, derfor bør man skrive 
ut ei feilmelding når det skjer.

Ta gjerne å eksperimenter med denne kode. Lag et program som kan multiplisere to 
tall. Lag  også et program som kan dividere, dvs at t1 blir divident og t2 blir divisor. 
Prøv også å skriv ut en litt annen tekst, i starten og slutten av programmet. Jobb litt 
med denne koden. Om du synes dette var mye rart å forholde seg til, så kan jeg 
trøste deg med at det blir egentlig ikke noe særlig mer komplisert enn dette.